/* Generated by S-function Builder */
#ifndef _MAX6691_BUS_H_
#define _MAX6691_BUS_H_
/* Read only - STARTS */
#ifdef MATLAB_MEX_FILE
#include "tmwtypes.h"
#else
#include "rtwtypes.h"
#endif




#ifndef DEFINED_TYPEDEF_FOR_maxHLstruct_
#define DEFINED_TYPEDEF_FOR_maxHLstruct_ 
typedef struct {
  uint32_T t1H;
  uint32_T t1L;
  uint32_T t2H;
  uint32_T t2L;
  uint32_T t3H;
  uint32_T t3L;
  uint32_T t4H;
  uint32_T t4L;
} maxHLstruct;
#endif


#ifndef DEFINED_TYPEDEF_FOR_maxTempStruct_
#define DEFINED_TYPEDEF_FOR_maxTempStruct_ 
typedef struct {
  real32_T t1;
  uint8_T t1_valid;
  real32_T t2;
  uint8_T t2_valid;
  real32_T t3;
  uint8_T t3_valid;
  real32_T t4;
  uint8_T t4_valid;
} maxTempStruct;
#endif

/* Read only - ENDS */


#endif
